### ISSUE TITLE
[SERVER] /list Api작성

### ISSUE THREAD

**Issue by sosick0418** [codestates/SSangdaeWithYou-server#7]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail:  흡연장소 list 구현과 상세정보 및 상세페이지 구현

### TODO
1. [ ] GET /list 요청을 받았을 때, 응답을 보내준다.
2. [ ] GET /detail 요청을 받았을 때, 응답을 보내준다.
3. [ ] Post /detail/comment 요청을 받았을 때, 응답을 보내준다.
4. [ ]  Post /detail/like or /dislike 요청을 받았을 때, 응답을 보내준다.

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 3h`
- Group :  `server`
- Urgency: `Middle`
